# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-05 14:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('vendor', models.CharField(max_length=50)),
                ('image', models.TextField()),
                ('description', models.TextField()),
                ('url', models.TextField()),
                ('category', models.ManyToManyField(related_name='catalog', to='blog.Category')),
            ],
        ),
    ]
